examples/websockets/websockets.c, src/onion/types.h, src/onion/websocket.h, tests/01-internal/14-websockets.c
The length argument of websocket callbacks can be negative on end-of-input
=> Websocket callbacks are called with -1 length on end-of-input

src/onion/poller_libevent.c
In commit 866793271147a7852f098e446c948f19e5ca27ec, a syntax error was
(probably inadvertently) added.  This fixes that error.
=> poller: Fix syntax error

src/onion/request_parser.c
If parse_PUT failed to write data to temp file, onion will leave the temp file opened.
=> Fix #122: close temp file fd when failed to write put body to temp file

src/bindings/cpp/url.cpp
Hi David,
When I changed the Url class to use automatic memory management, I missed the fact that the original Url object is still usable after a move. This pull request should fix that issue.
Thanks,
Zack
=> Fix Url memory leak.

src/bindings/cpp/dict.hpp
Hi,
I went back and reworked the code for locking/unlocking a Dict. I thought this approach might be more user friendly. The lock methods return a lock object that automatically releases the lock when the scope is exited.
Thanks,
Zack
=> Add methods for acquiring a read/write lock.

src/onion/onion.c, src/onion/types.h
O_THREADS_AVALIABLE should be correctly spelled as O_THREADS_AVAILABLE.
=> Fix spelling issue.

src/onion/onion.c
When looking at Issue #20, I discovered that the code that sets the
https certificates doesn't correctly initialize the listen point. This
causes a segfault when systemd support is compiled in. This initializes
the listen point correctly.
=> Fix null pointer dereference.

examples/multiport-cpp/multiport.cpp, src/bindings/cpp/http.hpp, src/bindings/cpp/https.hpp, src/bindings/cpp/listen_point.hpp, src/bindings/cpp/onion.hpp
This should makes things seem more natural with memory management. If the user doesn't assign a ListenPoint to an Onion object, the listen point will be freed like expected. It's also clear what the ownership semantics are as well.
=> Switched to move semantics to make things more natural.

src/onion/https.c
In the https connector we are initializing the priority cache twice. This leaks memory. I chose to use the initialization line with the more secure settings as it seems SSL3 is on its way out. If these settings are wrong I can change them.
=> A memory leak is created when initializing the priority cache.

examples/otop/CMakeLists.txt, src/onion/poller_libev.c
When building with libev on Fedora 23, otop isn't linking because of undefined references to libev functions. Also, I'm getting warnings about implicitly declared functions that reference onion_low* functions. This fixes that.
=> Fix build with libev.

src/bindings/cpp/shortcuts.cpp
After the changes I made to the Onion::Dict class, we are unneccessarily
increasing the ref count on the context dict. This causes a memory leak
when calling Onion::render_to_response.
=> Fix memory leak when calling Onion::render_to_response.

src/onion/dict.c
The ctype macros isspace and isdigit take an int instead of a char, and
they expect the input to be representable as an unsigned char or the EOF
macro. In this case we were passing the char directly, which could lead
to undefined behavior. This issue was pointed out by Solar Designer on
the mailing list.
=> Fix undefined behavior in dict.c.

src/onion/codecs.c, src/onion/mime.c, src/onion/request.c, src/onion/request_parser.c, src/onion/url.c
Onion shouldn't depend on the current locale for classifying characters, this should fix that. The one exception to this rule is when parsing /etc/mime.types, I don't think it matters in that case. Also, some formatting was fixed to be more consistent with the rest of the files.
=> Fix locale dependency

src/onion/log.c
This patch removes the mutex in the logging code. It also makes sure that we only initialize the logging once, instead of on every call to the logging code.
=> Fix logging mutex

src/onion/log.c
The localtime function uses a global data structure and a call to the
localtime function can clobber this when called from multiple threads
concurrently. I changed the call to localtime_r which uses a stack
allocated structure to store the data. This removes a data race
condition.
=> localtime call isn't reentrant.

src/onion/https.c
Onion was using functions that were deprecated with gcrypt 1.6.
Implemented a check for the gcrypt version that should fix this.
=> Fix issues with gcrypt 1.6

tools/otemplate/list.c, tools/otemplate/list.h, tools/otemplate/otemplate.c
When compiling libonion with Clang's address sanitizer, this memory leak
prevents compilation due to otemplate leaking memory. This commit fixes the
memory leak.
=> Fix a memory leak found in otemplate.

src/onion/codecs.c
We were incorrectly calculating the size of the new string, &amp; is 5
characters and not 4. This creates a buffer overflow condition in
onion_html_quote.
=> Fix issue with html quoting and a buffer overflow.

src/onion/request.c, src/onion/request.h
* Added some checks to onion_request_advance_path, which silently
ignores errors, for now.
* Changed the position parameter to off_t instead of int, may break
ABI compatibility
* Updated copyright and corrected some typos in the license header.
=> Add some checks to onion_request_advance path.

src/onion/codecs.c, src/onion/https.c, src/onion/random-gnutls.c
When building onion on CentOS 6, the version of gnutls available is
ancient. This works around some missing functions not available in older
versions of gnutls.
=> CentOS 6 SSL build

src/onion/poller.c
Hi David!
This is the patch I posted to the onion-dev list a while ago.  It isn't exactly clean, but it does the job of making onion work for me seemingly reliably for now (and faster than before, too), and I am not currently aware of any remaining fd or data race conditions in the poller with this patch applied, assuming that the epoll one-shot property works perfectly.  (There may still be issues with fd's getting closed on error by other parts of onion, which would trigger races in the poller again.  You might want to look into that.)
I think the fixtimeouts branch is a dead-end (slow, and possibly a less complete fix), at least for the time being, and this patch should be merged instead.  This way, we can announce that there were those fatal reliability and security bugs when running …
=> Race condition fixes using the shutdown() trick, timeout handling speedup, slots preallocation

src/onion/response.c
Running the hello example with clang's thread sanitizer found this data
race. We should be using the reentrant version of this function instead.
=> Replaced localtime call with localtime_r instead.

src/bindings/cpp/handler.hpp, src/bindings/cpp/url.cpp, src/bindings/cpp/url.hpp, tests/08-cpp/03-urls.cpp
Url now inherits from Handler. Removed the add method for Url that takes a
universal reference to another Url, as this is not needed now, as a Url is a
Handler. Also, updated the test now that a lambda isn't needed to invoke a Url.
=> This should address Issue #73.

src/onion/response.c
We need to lock on the reading of onion_response_last_time as it's
protected by the onion_response_date_lock.
=> Added a call to the pthread_rwlock_rdlock.

src/onion/response.c
Hi!
Here is a simple bugfix for some quirks with inputs larger than 512 bytes in `response.c:onion_response_vprintf`:
- the `va_list args` parameter was used twice, which is an undefined behavior (see `man 3 va_copy`), leading to segfaults on my machine;
- the second `vsnprintf`’s output was truncated, leading to the sending of a NUL character.
Beware: I have been unable to run the tests (couldn’t find how to do in `README.md`), therefore this request might break everything…
Sincerely,
=> Bugfix in `onion_response_vprintf`

src/bindings/cpp/url.hpp
This should allow a user to properly subclass and override the operator()
in Url.
=> Add the virtual keyword to operator() in Url.

examples/websockets/websockets.c, src/onion/response.c, src/onion/websocket.c, src/onion/websocket.h, tests/01-internal/14-websockets.c
Hi, 
With chrome 51 when closing websocket from the client by doing ws.close(1000), an error is thrown:
> WebSocket connection to 'ws://localhost:8080/' failed: Received a broken close frame containing invalid UTF-8.
I fixed this error, and another appeared:
> WebSocket connection to 'ws://localhost:3000/' failed: One or more reserved bits are on: reserved1 = 0, reserved2 = 1, reserved3 = 1
Putting the OR_LENGTH_SET flag to all WS connections did resolve the issue.
To reproduce the issue:
1. Compile the examples/websockets.c with a button that does ws.close(1000); (or use my modified version)
2. Launch ./websockets 
3. Launch http://localhost:8080/ with Chrome 51.0.2704.79 (64-bit)
4. Open the log console
5. Close the WebSocket from the server
I also made some unit tests to check that …
=> Chrome websocket fix and unit tests

src/onion/request.c
The memory allocated here wasn't being freed: https://github.com/davidmoreno/onion/blob/master/src/onion/request_parser.c#L1029
Requests causing the issue were in the form of:
https://gist.github.com/novcn/7accf1dc05a4fe6a490ba64076a3c238
where the amount of memory that was lost was equal to the size of the malloc above for each request.
=> Memory leak caused by multipart

src/onion/poller_libev.c, src/onion/poller_libevent.c
Uses named semaphores instead of unnamed semaphores as unnamed semaphores are deprecated for MAC OSX (http://stackoverflow.com/questions/1413785/sem-init-on-os-x).
I have kept the name of the semaphore to be "/poller". I checked all that most of the test cases were passing. On my system 11, 13 and 17 failed due to some reason but they were failing too even before the changes were made, I am still looking into the matter on why they failed or how can they be resolved.
=> Fixes #119

src/bindings/cpp/extrahandlers.cpp
The extra handlers used to be defined in the global namespace rather than Onion, so client code would compile against the headers, but throw up undefined references at link time. This patch defines the handlers in Onion so that linking succeeds.
=> Define C++ extra handlers in the correct namespace to fix linking

src/onion/handlers/auth_pam.c
Hello,
When I am compiling onion on my box, I am getting next warnings (actually, it may lead to errors as you know):
```
onion/src/onion/handlers/auth_pam.c: In function ‘onion_handler_auth_pam_handler’:
onion/src/onion/handlers/auth_pam.c:93: warning: implicit declaration of function ‘sprintf’
onion/src/onion/handlers/auth_pam.c:93: warning: incompatible implicit declaration of built-in function ‘sprintf’
```
The problem is that the file `<stdio.h>` is not included.
```
% cat /etc/redhat-release
CentOS release 6.9 (Final)
% uname -a
Linux localhost.localdomain 2.6.32-696.6.3.el6.x86_64 #1 SMP Wed Jul 12 14:17:22 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
% gcc -v
Using built-in specs.
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man …
```
=> auth_pam.c: sprintf in stdio.h

tools/otemplate/parser.c, tools/otemplate/parser.h
Fix issue #224
The source code of parser.c & parser.h has been indented in GNU style with indent -gnu
=>     Add ability to skip and parse with {# template comments #}

src/onion/low.c
In usage from low.c line 139, `snprintf` output could be between 32 and 50 bytes with `%ld` flag
This is the last warning that I'm seeing when compiling libonion as a subproject, excluding the tests folder
=> Fix gcc 8 warning about MEMORY_FAILURE macro

src/onion/shortcuts.c
See <http://man7.org/linux/man-pages/man2/sendfile.2.html> - notes section
Documented limitation for sendfile to work with no more than 0x7ffff000 bytes of data.
=> Bugfix for file serving > 2GB - don't use sendfile

examples/oterm/CMakeLists.txt
Building the project with `ninja` backend resulted in
ninja: error: '../examples/oterm/static/*', needed by 'examples/oterm/oterm_data.c', missing and no known rule to make it
Fix this by using CMake built-in functional to list all files
=> Fix ninja build by not relying on shell expansion

src/onion/handlers/auth_pam.c, src/onion/handlers/path.c, src/onion/handlers/path.h
There is a small typo in src/onion/handlers/auth_pam.c, src/onion/handlers/path.c, src/onion/handlers/path.h.
Should read `removes` rather than `reomves`.
=> docs: fix simple typo, reomves -> removes

src/onion/response.c, src/onion/response.h, tests/01-internal/03-response.c
Linked issue #281 and patch to #282
Output of the test:
```
$ tests/01-internal/03-response                            
03-response.c:43 INFO Test t01_create_add_free
[DB7D2A00] [2021-01-08 12:53:58] [ERROR response.c:279] Bad formed response. Need a request at creation. Will not write headers.
03-response.c:57 INFO t01_create_add_free ends: 3 succeses / 0 failures
03-response.c:61 INFO Test t02_full_cycle_http10
[DB7D2A00] [2021-01-08 12:53:58] [INFO response.c:191] [(null)] "GET (null)" 200 30 (Close connection)
03-response.c:95 INFO t02_full_cycle_http10 ends: 8 succeses / 0 failures
03-response.c:99 INFO Test t03_full_cycle_http11
[DB7D2A00] [2021-01-08 12:53:58] [INFO response.c:191] [(null)] "GET /" 200 30 (Keep-Alive)
03-response.c:137 INFO t03_full_cycle_http11 ends: 8 succeses / …
```
=> Adding support of SameSite cookies (based on the master branch)

src/onion/response.c
This gives a better warning when something is wrong. I needed it for the [RefPerSys](http://refpersys.org/) project.
=> better error message in onion_response_flush

src/onion/request.c, src/onion/request.h
In some projects (including [bismon](https://github.com/bstarynk/bismon/) and perhaps later [RefPerSys](http://refpersys.org/)) it could be useful to get a literal string giving the method name (e.g. "GET" or "POST" etc...) for a given Onion web-request.
This patch declares and defines a new `onion_request_get_method_name` function. The API of LibOnion changes compatibly
If accepted, a future patch might be proposed to add a C++ binding to that function (for the [RefPerSys](http://refpersys.org/) project).
Regards from [Basile Starynkevitch](http://starynkevitch.net/Basile/) (near Paris, in France) - you may email me to <basile@starynkevitch.net>
=> adding onion_request_get_method_name

src/bindings/cpp/request.hpp
This patch adds a C++ binding to `onion_request_get_method_name`. Such a patch could be useful to the [RefPerSys](http://refpersys.org/) project.
In my opinion, `ONION_VERSION_MINOR` should also be incremented to reflect this API improvement, but I don't know how to do that.
Regards from [Basile Starynkevitch](http://starynkevitch.net/Basile/) (near Paris, in France). Email me to [basile@starynkevitch.net](mailto:basile@starynkevitch.net) if needed.
=> adding C++ Onion::Request::Method_Name

src/onion/random-default.c
Hi! First time contributing here so please let me know if there's anything else needed for the PR.
Reading from /dev/random might return less than the expected amount of bytes, and that should be okay. We can just keep reading until we have enough bytes.
(imo it'd probably [be better to use /dev/urandom here](https://www.2uo.de/myths-about-urandom/ ) and we could even read from /dev/urandom on each call to `onion_random_generate`, but this change should avoid making the program exit without changing the random implementation too much)
=> random-default.c: Don't exit if we read less bytes from /dev/random

tests/01-internal/06-onion.c
Hello, I suspect that the project uses an improper `sizeof` value when calling `malloc` inside the tests file. We are creating an array of `pthread_t` so we should call `malloc` with `sizeof(pthread_t)`, but we use the size of the pointer instead. 
The execution might run fine because `pthread_t` and `pthread_t *` can have the same size (both are 8 bytes on my machine), but that is not necessarily true. 
I think that we should change it.
=> 06-onion.c: Fix value of 'sizeof' when allocating 'pthread_t' array with 'malloc'

src/bindings/cpp/response.hpp, src/onion/response.c
Hi,
I ran Cppcheck for static code analysis on the project and noticed that we have these 4 parameters that are non-reference const objects even though we could use const reference types which might be more performant in the case of `std::string`. And looking at some other functions, it seems like `const std::string&` is preferred over `const std::string` in the rest of the project.
=> Change `const std::string` to `const std::string&`

examples/oterm/oterm_handler.c
We need to use `sizeof(random_chars) - 1` as a modulus for `random_chars` instead of `sizeof(random_chars)` because the first variant can also return `\0` in the middle of the generated c-string.
This resolves #301 .
=> Fix the value of a sizeof modulus when computing a random uuid.

src/onion/response.c, src/onion/response.h
It's a real status code, supported by almost all browsers. See https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/418.
=> Implement the BEST http status code in the universe, 418 I'm a teapot.

src/onion/low.h, src/onion/response.c
I have discovered an attack that allows you to attack any non-trivial programs that use onion. At the very least it allows you to spam the logs with a few hundred thousand useless messages, and maybe even deny service to other clients. And the worst part about it? You only need Firefox (maybe Chrome can do it as well, I haven't tested that) and a functional <kbd>F5</kbd> key.
1. Download, compile and run the source file below, it's a program that simulates a non-trivial onion app by writing 200000-something chars when requested at `<Your IP>:8080/teapot`.
2. Download [Mozilla's finest web browser](https://www.mozilla.org/ru/firefox/new/) if you don't have it already.
3. Open up Firefox and browse to `localhost:8080/teapot`.
4. Make sure the Firefox window is in focus and hold down the …
=> Fix a potential log spamming and DOS attack
